#!/bin/bash
set -e

# OneDrive Integration Setup Script
# Creates Azure AD app registration and populates .env file

APP_NAME="${APP_NAME:-OneDrive Integration Client}"
ENV_FILE=".env"

echo "🔧 OneDrive Integration Setup"
echo "=============================="
echo ""

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo "❌ Azure CLI not found. Install it: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if logged in, if not prompt login
echo "📝 Checking Azure login status..."
if ! az account show &> /dev/null; then
    echo "🔐 Not logged in. Opening browser for Azure login..."
    az login
fi

# Get tenant ID
echo "📋 Getting tenant ID..."
TENANT_ID=$(az account show --query tenantId -o tsv)
echo "   Tenant ID: $TENANT_ID"

# Check if app already exists
EXISTING_APP_ID=$(az ad app list --display-name "$APP_NAME" --query "[0].appId" -o tsv 2>/dev/null || true)

if [ -n "$EXISTING_APP_ID" ]; then
    echo ""
    echo "⚠️  App '$APP_NAME' already exists with ID: $EXISTING_APP_ID"
    read -p "   Use existing app? [Y/n] " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo "   Exiting. Delete the existing app first or set APP_NAME env var."
        exit 1
    fi
    APP_ID=$EXISTING_APP_ID
else
    # Create the app registration
    echo ""
    echo "🚀 Creating Azure AD app registration..."
    az ad app create \
        --display-name "$APP_NAME" \
        --sign-in-audience "AzureADMyOrg" \
        --enable-id-token-issuance true \
        --enable-access-token-issuance true \
        --public-client-redirect-uris "http://localhost" \
        --output none

    APP_ID=$(az ad app list --display-name "$APP_NAME" --query "[0].appId" -o tsv)
    echo "   Created app with ID: $APP_ID"

    # Add Microsoft Graph permissions
    echo ""
    echo "🔑 Adding Microsoft Graph permissions..."
    GRAPH_API="00000003-0000-0000-c000-000000000000"

    # User.Read (delegated)
    az ad app permission add --id "$APP_ID" \
        --api $GRAPH_API \
        --api-permissions e1fe6dd8-ba31-4d61-89e7-88639da4683d=Scope \
        --output none
    echo "   ✓ User.Read"

    # Files.Read.All (delegated)
    az ad app permission add --id "$APP_ID" \
        --api $GRAPH_API \
        --api-permissions df85f4d6-205c-4ac5-a5ea-6bf408dba283=Scope \
        --output none
    echo "   ✓ Files.Read.All"

    # Sites.Read.All (delegated)
    az ad app permission add --id "$APP_ID" \
        --api $GRAPH_API \
        --api-permissions 205e70e5-aba6-4c52-a976-6d2d46c48043=Scope \
        --output none
    echo "   ✓ Sites.Read.All"
fi

# Write .env file
echo ""
echo "📄 Writing $ENV_FILE..."
cat > "$ENV_FILE" << EOF
# Azure AD / Microsoft Graph credentials
# Generated by setup.sh on $(date)

AZURE_TENANT_ID=$TENANT_ID
AZURE_CLIENT_ID=$APP_ID
EOF

echo "   ✓ $ENV_FILE created"

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Run: poetry install"
echo "  2. Test with Python:"
echo ""
echo "     from azure.identity import DeviceCodeCredential"
echo "     from src.onedrive import OneDriveClient"
echo "     from src.settings import get_settings"
echo ""
echo "     settings = get_settings()"
echo "     credential = DeviceCodeCredential("
echo "         client_id=settings.azure_client_id,"
echo "         tenant_id=settings.azure_tenant_id,"
echo "     )"
echo "     client = OneDriveClient(credential=credential)"
echo "     # Follow the device code prompt to authenticate"
echo ""
